id = "dogxi-theme"
name = "Dogxi Theme"
version = "0.0.1"
schema_version = 1
authors = ["Dogxi <hi@dogxi.me>"]
description = "Dogxi Theme for Zed"
repository = "https://github.com/dogxii/dogxi-theme-zed"
